#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task driveControl()
{
	bool oneStick = false;

	while(true)
	{

		if(vexRT(Btn8U) == 1)
		{
			oneStick = true;
		}
		else if(vexRT(Btn7U) == 1)
		{
			oneStick = false;
		}

		if(!oneStick)
		{
			float speed = vexRT(Ch3);
			float turn = vexRT(Ch1);
			if(turn > 1)
			{
				motor[frontLeft] = speed;
				motor[backLeft] = speed;
				motor[frontRight] = speed - 0.5*turn;
				motor[backRight] = speed - 0.5*turn;
			}
			else if(turn < -1)
			{
				motor[frontLeft] = speed + 0.5*turn;
				motor[backLeft] = speed + 0.5*turn;
				motor[frontRight] = speed;
				motor[backRight] = speed;
			}
			else
			{
				motor[frontLeft] = speed;
				motor[backLeft] = speed;
				motor[frontRight] = speed;
				motor[backRight] = speed;
			}
		}
		else
		{
			motor[frontLeft] = (vexRT(Ch2) + vexRT(Ch1))/2.0;
			motor[backLeft] = (vexRT(Ch2) + vexRT(Ch1))/2.0;
			motor[frontRight] = (vexRT(Ch2) - vexRT(Ch1))/2.0;
			motor[backRight] = (vexRT(Ch2) - vexRT(Ch1))/2.0;
		}
	}
}

task clawControl()
{
	while(true)
	{
		if(vexRT(Btn5U)==1)
		{
			motor[claw] = 30;
		}
		else if(vexRT(Btn6U)==1)
		{
			motor[claw] = -30;
		}
		else
		{
			motor[claw] =0;
		}
	}
}

task usercontrol ()
{
  startTask(driveControl);
  startTask(clawControl);
  while (true)
  {
    wait1Msec(1000);
  }
}
