#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  armStopper,     sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           sidewaysBase,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBase,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightBase,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armRightTop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRightBottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armLeftTop,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armLeftBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftTwist,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightTwist,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

///////////////////////////////////////////////CONST VARS AND METHODS/////////////////////////////////

const float SENSITIVITY = 0.7; //%
const float WRAPS = 6.0;

void setArmMotors(int speed) {
	motor[armLeftTop] = speed;
	motor[armRightTop] = speed;
	motor[armLeftBottom] = speed;
	motor[armRightBottom] = speed;
}

void setTwistMotors(int speed) {
	motor[leftTwist] = speed;
	motor[rightTwist] = speed;
}

void moveBase(int leftMotor, int rightMotor) {
	motor[rightBase] = rightMotor;
	motor[leftBase] = leftMotor;
}

void launch() {
	setArmMotors(-40); //dont do this too long
	while(nMotorEncoder(rightTwist) > WRAPS * -360) {
		setTwistMotors(-127); //start twisting : Once it hits WRAPS rotations around, launch the arm
	}
	setArmMotors(127); //start arm
	waitUntil(SensorValue[armStopper] == 1);
	setArmMotors(0); //stop once sensor is triggered
	setTwistMotors(0);
	wait1Msec(500);
	while(nMotorEncoder(rightTwist) < -180) {
		setTwistMotors(127);
	}
	setTwistMotors(0);
}

void calibrateTwist() {
	if(nMotorEncoder[rightTwist] < -90) {
		while(nMotorEncoder[rightTwist] < -90) {
			setTwistMotors(40);
		}
	} else {
		while(nMotorEncoder[rightTwist] > 90) {
			setTwistMotors(-40);
		}
	}
	nMotorEncoder[rightTwist] = 0;
	setTwistMotors(0);
}

//////////////////////////////////////////////AUTONOMOUS CODE//////////////////////////////////////
void moveFor(int time, int dir) {
	moveBase(dir * 60, dir * 60);
	wait1Msec(time); //guesstimate (until encoders)
	moveBase(0, 0);
	wait1Msec(200);
}

void turn(int degrees) { //1 or -1
	int dir = degrees / abs(degrees);
	moveBase(dir * 80, -dir * 80);
	wait1Msec(6 * degrees); //guesstimate (until encoders)
	moveBase(0, 0);
	wait1Msec(200);
}

void raiseArmFor(int time) {
	setArmMotors(25); //when raising and lowering arm, assist with twist motors
	setTwistMotors(-127);
	wait1Msec(time);
	setArmMotors(0);
	setTwistMotors(0);
}

void slideFor(int time, int dir) {
	motor[sidewaysBase] = dir * 100;
	wait1Msec(time);
	motor[sidewaysBase] = 0;
	wait1Msec(200);
}

task autonomous() {
	turn(90);
	moveFor(600, 1);
	raiseArmFor(1500);
	moveFor(600, -1);
	slideFor(1000, -1);
	turn(90);
	moveFor(1000, -1);
	calibrateTwist();
	//launch() ##############COMMENTED FOR INSPECTION ONLY
}

////////////////////////////////////////////////////USER CONTROL CODE/////////////////////////////////////////

task checkBaseControls() {
	while(true) {

		///////////////////////////////MOVEMENT/////////////////////////Controller 1

		int forwardVelocity = vexRT[Ch3] * SENSITIVITY; //-----------------------------------left joystick up + down
		int turnVelocity = vexRT[Ch1] * SENSITIVITY; //--------------------------------------right joystick left + right

		if(abs(forwardVelocity) < 20) { //deadzone check
			forwardVelocity = 0;
		}
		if(abs(turnVelocity) < 10) {
			turnVelocity = 0;
		}

		moveBase(forwardVelocity + turnVelocity, forwardVelocity - turnVelocity); //move(left, right)
		if(vexRT[Btn5U] == 1) { //slide left-------------------------------------------------left top trigger
			motor[sidewaysBase] = -127;
		} else if(vexRT[Btn6U] == 1) {//slide right------------------------------------------right top trigger
			motor[sidewaysBase] = 127;
		} else {
			motor[sidewaysBase] = 0;
		}
	}
}

task checkArmControls {
	while(true) {

		////////////////////////////////////ARM/////////////////////////////Controller 2

		if(vexRT[Btn8DXmtr2] == 1) { //launch-----------------------------------------------right bottom button
			launch(); //auto pauses
		}

		if(vexRT[Ch2Xmtr2] > 50) { //raise and lower arm-------------right  joystick
			setArmMotors(90); //when raising and lowering arm, assist with twist motors
			setTwistMotors(-127);
		} else {
			setArmMotors(0); //when raising and lowering arm, assist with twist motors
			setTwistMotors(0);
		}

		/////////////////////////////////////TWIST/////////////////////////

		if(vexRT[Btn6UXmtr2] == 1) { //force twist positive and zero------------------------right top trigger
			setTwistMotors(40);
			nMotorEncoder[rightTwist] = 0;
		} else if(vexRT[Btn5UXmtr2] == 1) { //force twist negative and zero-----------------left top trigger
			setTwistMotors(-40);
			nMotorEncoder[rightTwist] = 0;
		} else {
			setTwistMotors(0);
		}

		if(vexRT[Btn7DXmtr2] == 1) { //calibrate the twist----------------------------------left bottom button
			calibrateTwist();
		}
	}
}

task usercontrol() {
	writeDebugStreamLine("avg batt: %d", nAvgBatteryLevel);
	startTask(checkBaseControls);
	startTask(checkArmControls);
	while(true) {
		if(vexRT[Btn6D] == 1 && vexRT[Btn6U] == 1 && vexRT[Btn5D] == 1 && vexRT[Btn5U] == 1) {//kill switch-all triggers at the same time
			stopAllTasks();
		}
	}
}
