#pragma config(Motor,  port1,           fl,            tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           bl,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           fr,            tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           br,            tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		int leftSpeed = vexRT[Ch3];
		int rightSpeed = vexRT[Ch2];
		if(abs(leftSpeed) > 30) {
			motor[fl] = leftSpeed;
			motor[bl] = leftSpeed;
		} else {
			motor[fl] = 0;
			motor[bl] = 0;
		}
		if(abs(rightSpeed) > 30) {
			motor[fr] = rightSpeed;
			motor[br] = rightSpeed;
		} else {
			motor[fr] = 0;
			motor[br] = 0;
		}
	}
}
