#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  armStopper,     sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           frontLeft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armRightTop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armRightBottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           armLeftTop,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           armLeftBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           leftTwist,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rightTwist,    tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const float SENSITIVITY = 0.8; //%
const float WRAPS = 5.0;

void setArmMotors(int speed) {
	motor[armLeftTop] = speed;
	motor[armRightTop] = speed;
	motor[armLeftBottom] = speed;
	motor[armRightBottom] = speed;
}

void setTwistMotors(int speed) {
	motor[leftTwist] = speed;
	motor[rightTwist] = speed;
}

void moveBase(int leftMotors, int rightMotors) {
	motor[frontRight] = rightMotors;
	motor[backRight] = rightMotors;
	motor[frontLeft] = leftMotors;
	motor[backLeft] = leftMotors;
}

task checkBaseControls() {
	while(true) {
		///////////////////////////////////MOVEMENT
		int forwardVelocity = vexRT[Ch3] * SENSITIVITY;
		int sidewaysVelocity = vexRT[Ch4];
		if(abs(forwardVelocity) < 10) { //deadzone check
			forwardVelocity = 0;
		}
		if(abs(sidewaysVelocity) < 10) {
			sidewaysVelocity = 0;
		}
		moveBase(forwardVelocity + sidewaysVelocity, forwardVelocity - sidewaysVelocity); //move(left, right)
	}
}

task checkArmControls {
	while(true) {
		//////////////////////////////////ARM
		if(vexRT[Btn8D] == 1) { //if up button is pressed raise the arm until sensor is pressed
			setArmMotors(-30); //dont do this too long
			while(nMotorEncoder(rightTwist) > WRAPS * -360) {
				setTwistMotors(-127); //start twisting : Once it hits WRAPS rotations around, launch the arm
			}
			setArmMotors(127); //start arm
			waitUntil(SensorValue[armStopper] == 1);
			setArmMotors(0); //stop once sensor is triggered
			setTwistMotors(0);
			wait1Msec(500);
			while(nMotorEncoder(rightTwist) < 0) {
				setTwistMotors(127);
			}
			setTwistMotors(0);
		} else if(vexRT[Btn8R] == 1) { //else if down button is pressed lower the arm
			setArmMotors(-10);
		} else { //if no buttons are pressed stop the arm 0
			setArmMotors(0);
		}
		///////////////////////////////////TWIST
		if(vexRT[Btn6U] == 1) {//calibrate twisting
			setTwistMotors(20);
			nMotorEncoder[rightTwist] = 0;
		} else if(vexRT[Btn5U] == 1) {
			setTwistMotors(-20);
			nMotorEncoder[rightTwist] = 0;
		} else {
			setTwistMotors(0);
		}
	}
}

task main() {
	writeDebugStreamLine("batt: %d", nAvgBatteryLevel);
	if(nAvgBatteryLevel < 7.0) { //if battery is too low
		writeDebugStreamLine("batt below 7V");
		moveBase(10, 10);
		wait1Msec(400);
		moveBase(-10, -10);
		wait1Msec(400);
		moveBase(10, 10);
		wait1Msec(400);
		moveBase(-10, -10);
		wait1Msec(400);
		moveBase(0, 0);
	}
	startTask(checkBaseControls);
	startTask(checkArmControls);
	while(true) {
		if(vexRT[Btn6D]) {//kill switch bottom right
			stopAllTasks();
		}
	}
}
