#pragma config(Motor,  port1,           rightTop,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightBot,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftTop,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBot,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftBase,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightBase,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armLock,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          sidewaysBase,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const float SENSITIVITY = 0.7; //%
const float WRAPS = 5;

void setTwistMotors(int amount) {
	motor[rightTop] = amount;
	motor[leftTop] = amount;
	motor[rightBot] = amount;
	motor[leftBot] = amount;

}

void moveBase(int leftMotor, int rightMotor) {
	motor[rightBase] = rightMotor;
	motor[leftBase] = leftMotor;
}

void unlock() {
	motor[armLock] = 127;
	wait1Msec(400);
	motor[armLock] = 60;
}

void lock() {
	motor[armLock] = -127;
	wait1Msec(100);
	motor[armLock] = 0;
}

task base() {
	while(true) {
		if(vexRT[Btn8D] == 1) {
			setTwistMotors(127);
		} else if(vexRT[Btn8U] == 1) {
			setTwistMotors(-127);
		} else {
			setTwistMotors(0);
		}
		int forwardVelocity = vexRT[Ch3] * SENSITIVITY; //-----------------------------------left joystick up + down
		int turnVelocity = vexRT[Ch1] * SENSITIVITY; //--------------------------------------right joystick left + right

		if(abs(forwardVelocity) < 20) { //deadzone check
			forwardVelocity = 0;
		}
		if(abs(turnVelocity) < 10) {
			turnVelocity = 0;
		}

		moveBase(forwardVelocity + turnVelocity, forwardVelocity - turnVelocity); //move(left, right)

		if(vexRT[Btn5U] == 1) { //slide left-------------------------------------------------left top trigger
			motor[sidewaysBase] = -127;
		} else if(vexRT[Btn6U] == 1) {//slide right------------------------------------------right top trigger
			motor[sidewaysBase] = 127;
		} else {
			motor[sidewaysBase] = 0;
		}
	}
}

task arm() {
	while(true) {
		if(vexRT[Btn8DXmtr2] == 1) { //prepare launch---------------------------------------right bottom button
			while(vexRT[Btn8DXmtr2] == 1) {//actual launch------------------------------------release right bottom button
				while(nMotorEncoder(rightTop) < 3 * 360) {
					setTwistMotors(127); //pre-twist : Once it hits 4 rotations around, keep it there
				}
			}
			while(nMotorEncoder(rightTop) < WRAPS * 360) {
					setTwistMotors(127); //start twisting : Once it hits WRAPS rotations around, launch the arm
				}
			unlock();
			setTwistMotors(0);
			wait1Msec(500);
			while(nMotorEncoder(rightTop) > 180) {
				setTwistMotors(-127);
			}
			setTwistMotors(0);
			lock();
		}
	}
}

task main() {
	while(true) {
		if(vexRT[Btn8D] == 1) {
			motor[armLock] = 127;
		} else {
			motor[armLock] = 0;
		}
	}
}
